### ISSUE TITLE
Age of each subject

### ISSUE THREAD

**Issue by Tian-A-Tan** [hanxingjian/GroundLink#1]
Hello,

Thank you for sharing your data. Could you provide the exact age of each subject? This information is not covered by the table 2 of your publication.

Thank you!

**Comment by hanxingjian** [comment]
> Hello,
> 
> Thank you for sharing your data. Could you provide the exact age of each subject? This information is not covered by the table 2 of your publication.
> 
> Thank you!

Hi!

Please see the below list for the participants' age: 
1. 22
2. 21
3. 23
4. 20
5. 24
6. 35
7. 22

We mostly invited college students for capturing. 

Thanks,
XJ
